### ISSUE TITLE
Endoscope

### ISSUE THREAD

**Issue by YJonmo** [madhubabuv/undemon#3]
Hi there,

I would like to train this model on my own stereo endoscopic videos, obtained in the water. 

Is there anything that I should do extra compared with KITTI data?

Regards,
Jacob

**Comment by madhubabuv** [comment]
Yes, you may have to write a small script to prepare your data similar to prepare_train_data_stereo.py.

**Comment by YJonmo** [comment]
Thank you for your reply. I will start working on it soonish.
