### ISSUE TITLE
Pose_exp_net?

### ISSUE THREAD

**Issue by fengziyue** [madhubabuv/undemon#4]
When I run the test_kitti_pose.py
it says that can't find the pose_exp_net, so how should I solve it? I see in the nets there is a pose_net but no pose_exp_net, should I just use the pose_net?

**Comment by fengziyue** [comment]
@madhubabuv 
Thank you!

**Comment by fengziyue** [comment]
And, for evaluation, should I download the ground truth of depth and pose from kitti website by myself?

**Comment by madhubabuv** [comment]
Please use the name as 'pose-net'.

Yes, the depth evaluation can be done using lidar points and the pose evaluation can be done using the official odometry poses released with the dataset.
